In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Churn.csv')

In [3]:
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [5]:
df.drop(['customerID'],axis=1,inplace=True)

In [6]:
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  Female              0     Yes         No       1           No   
1    Male              0      No         No      34          Yes   
2    Male              0      No         No       2          Yes   
3    Male              0      No         No      45           No   
4  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity OnlineBackup  \
0  No phone service             DSL             No          Yes   
1                No             DSL            Yes           No   
2                No             DSL            Yes          Yes   
3  No phone service             DSL            Yes           No   
4                No     Fiber optic             No           No   

  DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0               No          No          No              No  Month-to-month   
1              Yes          No          No              No        One year   
2               No          No          No              No  Month-to-month   
3              Yes         Yes          No              No        One year   
4               No          No          No              No  Month-to-month   

  PaperlessBilling              PaymentMethod  MonthlyCharges TotalCharges  \
0              Yes           Electronic check           29.85        29.85   
1               No               Mailed check           56.95       1889.5   
2              Yes               Mailed check           53.85       108.15   
3               No  Bank transfer (automatic)           42.30      1840.75   
4              Yes           Electronic check           70.70       151.65   

  Churn  
0    No  
1    No  
2   Yes  
3    No  
4   Yes

In [7]:
df.shape

(7043, 20)

In [8]:
df.isna().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [9]:
df['TotalCharges'].unique()

array(['29.85', '1889.5', '108.15', ..., '346.45', '306.6', '6844.5'],
      dtype=object)

In [10]:
df['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [11]:
df['SeniorCitizen'].unique()

array([0, 1], dtype=int64)

In [12]:
df['Partner'].unique()

array(['Yes', 'No'], dtype=object)

In [13]:
df['Dependents'].unique()

array(['No', 'Yes'], dtype=object)

In [14]:
df['tenure'].unique()

array([ 1, 34,  2, 45,  8, 22, 10, 28, 62, 13, 16, 58, 49, 25, 69, 52, 71,
       21, 12, 30, 47, 72, 17, 27,  5, 46, 11, 70, 63, 43, 15, 60, 18, 66,
        9,  3, 31, 50, 64, 56,  7, 42, 35, 48, 29, 65, 38, 68, 32, 55, 37,
       36, 41,  6,  4, 33, 67, 23, 57, 61, 14, 20, 53, 40, 59, 24, 44, 19,
       54, 51, 26,  0, 39], dtype=int64)

In [15]:
df['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [16]:
df['DeviceProtection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [17]:
df['TotalCharges']=pd.to_numeric(df['TotalCharges'],errors='coerce')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


In [19]:
df.isna().sum()

gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [20]:
p=df['TotalCharges'].mean()

In [21]:
df['TotalCharges'].fillna(p,inplace=True)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null   object 


In [23]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [24]:
x=df[['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges']]

In [25]:
y=df['Churn']

In [26]:
x_cat_cols=x.select_dtypes(include='object')
x_num_cols=x.select_dtypes(include='number')

In [27]:
x_cat_cols.head()

gender Partner Dependents PhoneService     MultipleLines InternetService  \
0  Female     Yes         No           No  No phone service             DSL   
1    Male      No         No          Yes                No             DSL   
2    Male      No         No          Yes                No             DSL   
3    Male      No         No           No  No phone service             DSL   
4  Female      No         No          Yes                No     Fiber optic   

  OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   
2            Yes          Yes               No          No          No   
3            Yes           No              Yes         Yes          No   
4             No           No               No          No          No   

  StreamingMovies        Contract PaperlessBilling              PaymentMethod  
0              No  Month-to-month              Yes           Electronic check  
1              No        One year               No               Mailed check  
2              No  Month-to-month              Yes               Mailed check  
3              No        One year               No  Bank transfer (automatic)  
4              No  Month-to-month              Yes           Electronic check

In [28]:
x_cat_cols=pd.get_dummies(x_cat_cols,dtype=int)
x_cat_cols.head

<bound method NDFrame.head of       gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  \
0                 1            0           0            1              1   
1                 0            1           1            0              1   
2                 0            1           1            0              1   
3                 0            1           1            0              1   
4                 1            0           1            0              1   
...             ...          ...         ...          ...            ...   
7038              0            1           0            1              0   
7039              1            0           0            1              0   
7040              1            0           0            1              0   
7041              0            1           0            1              1   
7042              0            1           1            0              1   

      Dependents_Yes  PhoneService_No  PhoneService_Yes  

In [29]:
x=pd.concat([x_cat_cols,x_num_cols],axis=1)

In [30]:
pd.set_option('display.max_columns',None)

In [31]:
x.head()

gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  \
0              1            0           0            1              1   
1              0            1           1            0              1   
2              0            1           1            0              1   
3              0            1           1            0              1   
4              1            0           1            0              1   

   Dependents_Yes  PhoneService_No  PhoneService_Yes  MultipleLines_No  \
0               0                1                 0                 0   
1               0                0                 1                 1   
2               0                0                 1                 1   
3               0                1                 0                 0   
4               0                0                 1                 1   

   MultipleLines_No phone service  MultipleLines_Yes  InternetService_DSL  \
0                               1                  0                    1   
1                               0                  0                    1   
2                               0                  0                    1   
3                               1                  0                    1   
4                               0                  0                    0   

   InternetService_Fiber optic  InternetService_No  OnlineSecurity_No  \
0                            0                   0                  1   
1                            0                   0                  0   
2                            0                   0                  0   
3                            0                   0                  0   
4                            1                   0                  1   

   OnlineSecurity_No internet service  OnlineSecurity_Yes  OnlineBackup_No  \
0                                   0                   0                0   
1                                   0                   1                1   
2                                   0                   1                0   
3                                   0                   1                1   
4                                   0                   0                1   

   OnlineBackup_No internet service  OnlineBackup_Yes  DeviceProtection_No  \
0                                 0                 1                    1   
1                                 0                 0                    0   
2                                 0                 1                    1   
3                                 0                 0                    0   
4                                 0                 0                    1   

   DeviceProtection_No internet service  DeviceProtection_Yes  TechSupport_No  \
0                                     0                     0               1   
1                                     0                     1               1   
2                                     0                     0               1   
3                                     0                     1               0   
4                                     0                     0               1   

   TechSupport_No internet service  TechSupport_Yes  StreamingTV_No  \
0                                0                0               1   
1                                0                0               1   
2                                0                0               1   
3                                0                1               1   
4                                0                0               1   

   StreamingTV_No internet service  StreamingTV_Yes  StreamingMovies_No  \
0                                0                0                   1   
1                                0                0                   1   
2                                0                0                   1   
3                                0                0              

In [32]:
x.columns

Index(['gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_

In [33]:
x.shape

(7043, 45)

In [34]:
features=['gender_Female', 'gender_Male', 'Partner_No', 'Partner_Yes',
       'Dependents_No', 'Dependents_Yes', 'PhoneService_No',
       'PhoneService_Yes', 'MultipleLines_No',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_DSL', 'InternetService_Fiber optic',
       'InternetService_No', 'OnlineSecurity_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No', 'OnlineBackup_No internet service',
       'OnlineBackup_Yes', 'DeviceProtection_No',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No', 'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No', 'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No', 'StreamingMovies_No internet service',
       'StreamingMovies_Yes', 'Contract_Month-to-month', 'Contract_One year',
       'Contract_Two year', 'PaperlessBilling_No', 'PaperlessBilling_Yes',
       'PaymentMethod_Bank transfer (automatic)',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check',
       'SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
x = StandardScaler().fit_transform(x)

In [37]:
x

array([[ 1.00955867, -1.00955867, -1.03453023, ..., -1.27744458,
        -1.16032292, -0.99497138],
       [-0.99053183,  0.99053183,  0.96662231, ...,  0.06632742,
        -0.25962894, -0.17387565],
       [-0.99053183,  0.99053183,  0.96662231, ..., -1.23672422,
        -0.36266036, -0.96039939],
       ...,
       [ 1.00955867, -1.00955867, -1.03453023, ..., -0.87024095,
        -1.1686319 , -0.85518222],
       [-0.99053183,  0.99053183, -1.03453023, ..., -1.15528349,
         0.32033821, -0.87277729],
       [-0.99053183,  0.99053183,  0.96662231, ...,  1.36937906,
         1.35896134,  2.01391739]])

In [38]:
pd.DataFrame(data = x, columns = features).head()

gender_Female  gender_Male  Partner_No  Partner_Yes  Dependents_No  \
0       1.009559    -1.009559   -1.034530     1.034530       0.654012   
1      -0.990532     0.990532    0.966622    -0.966622       0.654012   
2      -0.990532     0.990532    0.966622    -0.966622       0.654012   
3      -0.990532     0.990532    0.966622    -0.966622       0.654012   
4       1.009559    -1.009559    0.966622    -0.966622       0.654012   

   Dependents_Yes  PhoneService_No  PhoneService_Yes  MultipleLines_No  \
0       -0.654012         3.054010         -3.054010         -0.963330   
1       -0.654012        -0.327438          0.327438          1.038066   
2       -0.654012        -0.327438          0.327438          1.038066   
3       -0.654012         3.054010         -3.054010         -0.963330   
4       -0.654012        -0.327438          0.327438          1.038066   

   MultipleLines_No phone service  MultipleLines_Yes  InternetService_DSL  \
0                        3.054010          -0.854176             1.381712   
1                       -0.327438          -0.854176             1.381712   
2                       -0.327438          -0.854176             1.381712   
3                        3.054010          -0.854176             1.381712   
4                       -0.327438          -0.854176            -0.723740   

   InternetService_Fiber optic  InternetService_No  OnlineSecurity_No  \
0                    -0.885660           -0.525927           1.006696   
1                    -0.885660           -0.525927          -0.993349   
2                    -0.885660           -0.525927          -0.993349   
3                    -0.885660           -0.525927          -0.993349   
4                     1.129102           -0.525927           1.006696   

   OnlineSecurity_No internet service  OnlineSecurity_Yes  OnlineBackup_No  \
0                           -0.525927           -0.633933        -0.883620   
1                           -0.525927            1.577454         1.131709   
2                           -0.525927            1.577454        -0.883620   
3                           -0.525927            1.577454         1.131709   
4                           -0.525927           -0.633933         1.131709   

   OnlineBackup_No internet service  OnlineBackup_Yes  DeviceProtection_No  \
0                         -0.525927          1.378241             1.129427   
1                         -0.525927         -0.725563            -0.885405   
2                         -0.525927          1.378241             1.129427   
3                         -0.525927         -0.725563            -0.885405   
4                         -0.525927         -0.725563             1.129427   

   DeviceProtection_No internet service  DeviceProtection_Yes  TechSupport_No  \
0                             -0.525927             -0.723968        1.013869   
1                             -0.525927              1.381277        1.013869   
2                             -0.525927             -0.723968        1.013869   
3                             -0.525927              1.381277       -0.986321   
4                             -0.525927             -0.723968        1.013869   

   TechSupport_No internet service  TechSupport_Yes  StreamingTV_No  \
0                        -0.525927        -0.639439        1.227357   
1                        -0.525927        -0.639439        1.227357   
2                        -0.525927        -0.639439        1.227357   
3                        -0.525927         1.563872        1.227357   
4                        -0.525927        -0.639439        1.227357   

   StreamingTV_No internet service  StreamingTV_Yes  StreamingMovies_No  \
0                        -0.525927        -0.790132            1.236489   
1                        -0.525927        -0.790132            1.236489   
2                        -0.525927        -0.790132            1.236489   
3                        -0.525927        -0.790132            1.

In [39]:
from sklearn.decomposition import PCA

In [40]:
pca=PCA(n_components=20)

In [41]:
principlecomponents=pca.fit_transform(x)

In [42]:
pca.explained_variance_ratio_

array([0.25232238, 0.13502803, 0.09435648, 0.05642499, 0.05001685,
       0.04448535, 0.03711816, 0.0345879 , 0.03030861, 0.02878357,
       0.02846019, 0.02670603, 0.02583586, 0.02513736, 0.02370126,
       0.02190126, 0.02054891, 0.01931956, 0.01836085, 0.01698469])

In [43]:
principalDf = pd.DataFrame(data = principlecomponents, columns = ['principal component 1', 'principal component 2','principal component 3', 'principal component 4','principal component 5', 'principal component 6','principal component 7', 'principal component 8','principal component 9', 'principal component 10','principal component 11', 'principal component 12','principal component 13', 'principal component 14','principal component 15', 'principal component 16','principal component 17', 'principal component 18','principal component 19', 'principal component 20'])

In [44]:
principalDf.head()

principal component 1  principal component 2  principal component 3  \
0              -1.999615              -3.070152               4.544314   
1              -0.332762              -1.207431               1.834880   
2              -0.864564              -2.904843               1.089498   
3              -1.062124              -0.107728               6.372778   
4              -1.837310              -4.211000              -1.436396   

   principal component 4  principal component 5  principal component 6  \
0               1.136811               2.944256               1.773956   
1              -1.043905              -3.506867              -1.720115   
2              -1.124615              -2.357712              -1.321389   
3               2.000950              -1.610855              -1.489293   
4              -0.569003              -0.198811               1.450748   

   principal component 7  principal component 8  principal component 9  \
0              -1.956831              -0.777723               1.576285   
1               1.051570               0.781945               0.995812   
2              -0.739345              -2.311880               0.858456   
3              -0.406874               0.999279               0.109462   
4               0.096392              -0.682988              -0.212823   

   principal component 10  principal component 11  principal component 12  \
0               -1.223056               -0.163546                0.517415   
1                2.278725               -0.125673                0.089295   
2               -1.551201               -0.034215               -0.639976   
3                2.573241                1.784609                0.092053   
4                0.196484               -0.071875                0.428345   

   principal component 13  principal component 14  principal component 15  \
0                0.294180               -0.274176               -1.053564   
1                1.304847                2.201789                0.282609   
2                1.617986                0.974661                0.697872   
3               -0.051444                0.902342               -0.105200   
4                0.086676               -0.280926                0.082439   

   principal component 16  principal component 17  principal component 18  \
0               -0.446078                0.021092                0.689695   
1                0.648203               -0.332932                0.682800   
2                1.427182               -0.052855                0.674417   
3               -1.637846               -0.088803               -1.807673   
4               -1.159446                0.055816               -0.254039   

   principal component 19  principal component 20  
0               -0.050239               -1.527951  
1               -1.057504                0.339215  
2                0.183814               -0.155775  
3                0.154815               -0.373695  
4               -1.235064               -0.384988

In [45]:
df[['Churn']].head()

Churn
0    No
1    No
2   Yes
3    No
4   Yes

In [46]:
finalDf = pd.concat([principalDf, df[['Churn']]], axis = 1)
finalDf.head(5)

principal component 1  principal component 2  principal component 3  \
0              -1.999615              -3.070152               4.544314   
1              -0.332762              -1.207431               1.834880   
2              -0.864564              -2.904843               1.089498   
3              -1.062124              -0.107728               6.372778   
4              -1.837310              -4.211000              -1.436396   

   principal component 4  principal component 5  principal component 6  \
0               1.136811               2.944256               1.773956   
1              -1.043905              -3.506867              -1.720115   
2              -1.124615              -2.357712              -1.321389   
3               2.000950              -1.610855              -1.489293   
4              -0.569003              -0.198811               1.450748   

   principal component 7  principal component 8  principal component 9  \
0              -1.956831              -0.777723               1.576285   
1               1.051570               0.781945               0.995812   
2              -0.739345              -2.311880               0.858456   
3              -0.406874               0.999279               0.109462   
4               0.096392              -0.682988              -0.212823   

   principal component 10  principal component 11  principal component 12  \
0               -1.223056               -0.163546                0.517415   
1                2.278725               -0.125673                0.089295   
2               -1.551201               -0.034215               -0.639976   
3                2.573241                1.784609                0.092053   
4                0.196484               -0.071875                0.428345   

   principal component 13  principal component 14  principal component 15  \
0                0.294180               -0.274176               -1.053564   
1                1.304847                2.201789                0.282609   
2                1.617986                0.974661                0.697872   
3               -0.051444                0.902342               -0.105200   
4                0.086676               -0.280926                0.082439   

   principal component 16  principal component 17  principal component 18  \
0               -0.446078                0.021092                0.689695   
1                0.648203               -0.332932                0.682800   
2                1.427182               -0.052855                0.674417   
3               -1.637846               -0.088803               -1.807673   
4               -1.159446                0.055816               -0.254039   

   principal component 19  principal component 20 Churn  
0               -0.050239               -1.527951    No  
1               -1.057504                0.339215    No  
2                0.183814               -0.155775   Yes  
3                0.154815               -0.373695    No  
4               -1.235064               -0.384988   Yes

In [47]:
x=finalDf[['principal component 1', 'principal component 2','principal component 3', 'principal component 4','principal component 5', 'principal component 6','principal component 7', 'principal component 8','principal component 9', 'principal component 10','principal component 11', 'principal component 12','principal component 13', 'principal component 14','principal component 15', 'principal component 16','principal component 17', 'principal component 18','principal component 19', 'principal component 20']]
y=finalDf['Churn']

# K-NN

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=35,test_size=0.25)

In [49]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [50]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=7)
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [51]:
train_predictions=classifier.predict(x_train)
test_predictions=classifier.predict(x_test)

In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(test_predictions,y_test))

print(classification_report(test_predictions,y_test))

print("Train Accuracy:",accuracy_score(train_predictions,y_train)*100)
print("Test Accuracy:",accuracy_score(test_predictions,y_test)*100)

[[1100  203]
 [ 212  246]]
              precision    recall  f1-score   support

          No       0.84      0.84      0.84      1303
         Yes       0.55      0.54      0.54       458

    accuracy                           0.76      1761
   macro avg       0.69      0.69      0.69      1761
weighted avg       0.76      0.76      0.76      1761

Train Accuracy: 81.20030291556229
Test Accuracy: 76.43384440658717


# Naive Bayes

In [53]:
from sklearn.naive_bayes import GaussianNB

In [54]:
clf = GaussianNB(var_smoothing=0.001)
clf.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=0.001)

In [55]:
train_prediction=clf.predict(x_train)
test_prediction=clf.predict(x_test)

In [60]:
print("Train Accuracy: ",accuracy_score(y_train,train_prediction)*100)
print("Validation Accuracy: ",accuracy_score(y_test,test_prediction)*100)

Train Accuracy:  77.48958727754638
Validation Accuracy:  77.73992049971608


# SVM

In [61]:
from sklearn.svm import SVC

In [65]:
linear_svm = SVC(kernel='linear', C=100,gamma=0.1, random_state=10)
# Train the classifier
linear_svm.fit(x_train, y_train)

test_predictions=linear_svm.predict(x_test)
train_predictions=linear_svm.predict(x_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[1168  144]
 [ 195  254]]
              precision    recall  f1-score   support

          No       0.86      0.89      0.87      1312
         Yes       0.64      0.57      0.60       449

    accuracy                           0.81      1761
   macro avg       0.75      0.73      0.74      1761
weighted avg       0.80      0.81      0.80      1761

Train Accuracy: 79.49640287769785
Test Accuracy: 80.7495741056218


In [66]:
linear_svm = SVC(kernel='rbf', C=100,gamma=0.1, random_state=10)
# Train the classifier
linear_svm.fit(x_train, y_train)

test_predictions=linear_svm.predict(x_test)
train_predictions=linear_svm.predict(x_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[1101  211]
 [ 220  229]]
              precision    recall  f1-score   support

          No       0.83      0.84      0.84      1312
         Yes       0.52      0.51      0.52       449

    accuracy                           0.76      1761
   macro avg       0.68      0.67      0.68      1761
weighted avg       0.75      0.76      0.75      1761

Train Accuracy: 94.66111321469141
Test Accuracy: 75.5252697331062


In [67]:
linear_svm = SVC(kernel='poly', C=100,gamma=0.1, random_state=10)
# Train the classifier
linear_svm.fit(x_train, y_train)

test_predictions=linear_svm.predict(x_test)
train_predictions=linear_svm.predict(x_train)

print(confusion_matrix(y_test, test_predictions))

print(classification_report(y_test, test_predictions))

print("Train Accuracy:",accuracy_score(y_train, train_predictions)*100)
print("Test Accuracy:",accuracy_score(y_test, test_predictions)*100)

[[1052  260]
 [ 189  260]]
              precision    recall  f1-score   support

          No       0.85      0.80      0.82      1312
         Yes       0.50      0.58      0.54       449

    accuracy                           0.75      1761
   macro avg       0.67      0.69      0.68      1761
weighted avg       0.76      0.75      0.75      1761

Train Accuracy: 90.13631200302915
Test Accuracy: 74.50312322544009
